service: server

custom:
    secrets: ${file(secrets.json)}

provider:
    name: aws
    runtime: nodejs8.10
    timeout: 30
    stage: ${self:custom.secrets.NODE_ENV}
    environment:
        NODE_ENV: ${self:custom.secrets.NODE_ENV}
        DB_NAME: ${self:custom.secrets.DB_NAME}
        DB_USER: ${self:custom.secrets.DB_USER}
        DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
        DB_HOST: ${self:custom.secrets.DB_HOST}
        DB_PORT: ${self:custom.secrets.DB_PORT}
    vpc:
        securityGroupIds:
            - ${self:custom.secrets.SECURITY_GROUP_ID}
        subnetIds:
            - ${self:custom.secrets.SUBNET1_ID}
            - ${self:custom.secrets.SUBNET2_ID}
            - ${self:custom.secrets.SUBNET3_ID}
            - ${self:custom.secrets.SUBNET4_ID}

functions:
    server:
        handler: handler

plugins:
    - serverless-offline
