org: ssalbdivad
app: redo-server
service: redo-server
provider:
    name: aws
    runtime: nodejs12.x
    region: us-east-1
    vpc:
        securityGroupIds:
            - sg-01531bed584bbf052
        subnetIds:
            - subnet-0a611ede487934a7a
            - subnet-06e55108e697dfe38
            - subnet-047fc88b060a661d6
            - subnet-0142e0f910f3d3f44
            - subnet-0574c1f0759cd7b83
            - subnet-0ed2b49a68bb2f5a6
    environment:
        NODE_ENV: production
plugins:
    - serverless-dotenv-plugin
    # - serverless-hooks-plugin
    - serverless-plugin-typescript
    - serverless-offline
functions:
    graphql:
        handler: main.handler
        events:
            - http:
                  path: graphql
                  method: post
                  cors: true
            - http:
                  path: graphql
                  method: get
                  cors: true
# custom:
#     webpack:
#         webpackConfig: "webpack.config.ts"
#         includeModules:
#             forceExclude:
#                 - prisma2
#     hooks:
#         after:package:createDeploymentArtifacts:
#             - ts-node packageDependencies.ts
