version: 2
updates:
  - package-ecosystem: npm
    directory: /ark/attest
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /ark/repo
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /ark/fast-check
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /ark/regex
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /ark/json-schema
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /ark/type
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /ark/schema
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /ark/extension
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /ark/themes
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /ark/docs
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /ark/fs
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /ark/util
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-dependencies:
        patterns:
          - "*"
