/**
 * This file was automatically generated by GraphQL Nexus
 * Do not make changes to this file directly
 */

import * as photon from "@generated/photon"



declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  SelectorCreateInput: { // input type
    css: string; // String!
    steps?: NexusGenInputs['StepCreateManyWithoutStepsInput'] | null; // StepCreateManyWithoutStepsInput
    user?: NexusGenInputs['UserCreateOneWithoutUserInput'] | null; // UserCreateOneWithoutUserInput
  }
  SelectorCreateManyWithoutSelectorsInput: { // input type
    connect?: NexusGenInputs['SelectorWhereUniqueInput'][] | null; // [SelectorWhereUniqueInput!]
    create?: NexusGenInputs['SelectorCreateWithoutUserInput'][] | null; // [SelectorCreateWithoutUserInput!]
  }
  SelectorCreateOneWithoutSelectorInput: { // input type
    connect?: NexusGenInputs['SelectorWhereUniqueInput'] | null; // SelectorWhereUniqueInput
    create?: NexusGenInputs['SelectorCreateWithoutStepsInput'] | null; // SelectorCreateWithoutStepsInput
  }
  SelectorCreateWithoutStepsInput: { // input type
    css: string; // String!
    user?: NexusGenInputs['UserCreateOneWithoutUserInput'] | null; // UserCreateOneWithoutUserInput
  }
  SelectorCreateWithoutUserInput: { // input type
    css: string; // String!
    steps?: NexusGenInputs['StepCreateManyWithoutStepsInput'] | null; // StepCreateManyWithoutStepsInput
  }
  SelectorWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  StepCreateInput: { // input type
    action: string; // String!
    selector: NexusGenInputs['SelectorCreateOneWithoutSelectorInput']; // SelectorCreateOneWithoutSelectorInput!
    test?: NexusGenInputs['TestCreateOneWithoutTestInput'] | null; // TestCreateOneWithoutTestInput
    user?: NexusGenInputs['UserCreateOneWithoutUserInput'] | null; // UserCreateOneWithoutUserInput
    value: string; // String!
  }
  StepCreateManyWithoutStepsInput: { // input type
    connect?: NexusGenInputs['StepWhereUniqueInput'][] | null; // [StepWhereUniqueInput!]
    create?: NexusGenInputs['StepCreateWithoutSelectorInput'][] | null; // [StepCreateWithoutSelectorInput!]
  }
  StepCreateWithoutSelectorInput: { // input type
    action: string; // String!
    test?: NexusGenInputs['TestCreateOneWithoutTestInput'] | null; // TestCreateOneWithoutTestInput
    user?: NexusGenInputs['UserCreateOneWithoutUserInput'] | null; // UserCreateOneWithoutUserInput
    value: string; // String!
  }
  StepWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  TagCreateInput: { // input type
    name: string; // String!
    test?: NexusGenInputs['TestCreateOneWithoutTestInput'] | null; // TestCreateOneWithoutTestInput
    user: NexusGenInputs['UserCreateOneWithoutUserInput']; // UserCreateOneWithoutUserInput!
  }
  TagCreateManyWithoutTagsInput: { // input type
    connect?: NexusGenInputs['TagWhereUniqueInput'][] | null; // [TagWhereUniqueInput!]
    create?: NexusGenInputs['TagCreateWithoutTestInput'][] | null; // [TagCreateWithoutTestInput!]
  }
  TagCreateWithoutTestInput: { // input type
    name: string; // String!
    user: NexusGenInputs['UserCreateOneWithoutUserInput']; // UserCreateOneWithoutUserInput!
  }
  TagWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  TestCreateInput: { // input type
    name: string; // String!
    steps?: NexusGenInputs['StepCreateManyWithoutStepsInput'] | null; // StepCreateManyWithoutStepsInput
    tags?: NexusGenInputs['TagCreateManyWithoutTagsInput'] | null; // TagCreateManyWithoutTagsInput
    user: NexusGenInputs['UserCreateOneWithoutUserInput']; // UserCreateOneWithoutUserInput!
  }
  TestCreateManyWithoutTestsInput: { // input type
    connect?: NexusGenInputs['TestWhereUniqueInput'][] | null; // [TestWhereUniqueInput!]
    create?: NexusGenInputs['TestCreateWithoutUserInput'][] | null; // [TestCreateWithoutUserInput!]
  }
  TestCreateOneWithoutTestInput: { // input type
    connect?: NexusGenInputs['TestWhereUniqueInput'] | null; // TestWhereUniqueInput
    create?: NexusGenInputs['TestCreateWithoutStepsInput'] | null; // TestCreateWithoutStepsInput
  }
  TestCreateWithoutStepsInput: { // input type
    name: string; // String!
    tags?: NexusGenInputs['TagCreateManyWithoutTagsInput'] | null; // TagCreateManyWithoutTagsInput
    user: NexusGenInputs['UserCreateOneWithoutUserInput']; // UserCreateOneWithoutUserInput!
  }
  TestCreateWithoutUserInput: { // input type
    name: string; // String!
    steps?: NexusGenInputs['StepCreateManyWithoutStepsInput'] | null; // StepCreateManyWithoutStepsInput
    tags?: NexusGenInputs['TagCreateManyWithoutTagsInput'] | null; // TagCreateManyWithoutTagsInput
  }
  TestWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  UserCreateInput: { // input type
    email: string; // String!
    firstName: string; // String!
    lastName: string; // String!
    password: string; // String!
    selectors?: NexusGenInputs['SelectorCreateManyWithoutSelectorsInput'] | null; // SelectorCreateManyWithoutSelectorsInput
    steps?: NexusGenInputs['StepCreateManyWithoutStepsInput'] | null; // StepCreateManyWithoutStepsInput
    tags?: NexusGenInputs['TagCreateManyWithoutTagsInput'] | null; // TagCreateManyWithoutTagsInput
    tests?: NexusGenInputs['TestCreateManyWithoutTestsInput'] | null; // TestCreateManyWithoutTestsInput
  }
  UserCreateOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    create?: NexusGenInputs['UserCreateWithoutTagsInput'] | null; // UserCreateWithoutTagsInput
  }
  UserCreateWithoutTagsInput: { // input type
    email: string; // String!
    firstName: string; // String!
    lastName: string; // String!
    password: string; // String!
    selectors?: NexusGenInputs['SelectorCreateManyWithoutSelectorsInput'] | null; // SelectorCreateManyWithoutSelectorsInput
    steps?: NexusGenInputs['StepCreateManyWithoutStepsInput'] | null; // StepCreateManyWithoutStepsInput
    tests?: NexusGenInputs['TestCreateManyWithoutTestsInput'] | null; // TestCreateManyWithoutTestsInput
  }
  UserWhereUniqueInput: { // input type
    email?: string | null; // String
    id?: number | null; // Int
  }
}

export interface NexusGenEnums {
}

export interface NexusGenRootTypes {
  Mutation: {};
  Query: {};
  Selector: photon.Selector;
  Step: photon.Step;
  Tag: photon.Tag;
  Test: photon.Test;
  User: photon.User;
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  SelectorCreateInput: NexusGenInputs['SelectorCreateInput'];
  SelectorCreateManyWithoutSelectorsInput: NexusGenInputs['SelectorCreateManyWithoutSelectorsInput'];
  SelectorCreateOneWithoutSelectorInput: NexusGenInputs['SelectorCreateOneWithoutSelectorInput'];
  SelectorCreateWithoutStepsInput: NexusGenInputs['SelectorCreateWithoutStepsInput'];
  SelectorCreateWithoutUserInput: NexusGenInputs['SelectorCreateWithoutUserInput'];
  SelectorWhereUniqueInput: NexusGenInputs['SelectorWhereUniqueInput'];
  StepCreateInput: NexusGenInputs['StepCreateInput'];
  StepCreateManyWithoutStepsInput: NexusGenInputs['StepCreateManyWithoutStepsInput'];
  StepCreateWithoutSelectorInput: NexusGenInputs['StepCreateWithoutSelectorInput'];
  StepWhereUniqueInput: NexusGenInputs['StepWhereUniqueInput'];
  TagCreateInput: NexusGenInputs['TagCreateInput'];
  TagCreateManyWithoutTagsInput: NexusGenInputs['TagCreateManyWithoutTagsInput'];
  TagCreateWithoutTestInput: NexusGenInputs['TagCreateWithoutTestInput'];
  TagWhereUniqueInput: NexusGenInputs['TagWhereUniqueInput'];
  TestCreateInput: NexusGenInputs['TestCreateInput'];
  TestCreateManyWithoutTestsInput: NexusGenInputs['TestCreateManyWithoutTestsInput'];
  TestCreateOneWithoutTestInput: NexusGenInputs['TestCreateOneWithoutTestInput'];
  TestCreateWithoutStepsInput: NexusGenInputs['TestCreateWithoutStepsInput'];
  TestCreateWithoutUserInput: NexusGenInputs['TestCreateWithoutUserInput'];
  TestWhereUniqueInput: NexusGenInputs['TestWhereUniqueInput'];
  UserCreateInput: NexusGenInputs['UserCreateInput'];
  UserCreateOneWithoutUserInput: NexusGenInputs['UserCreateOneWithoutUserInput'];
  UserCreateWithoutTagsInput: NexusGenInputs['UserCreateWithoutTagsInput'];
  UserWhereUniqueInput: NexusGenInputs['UserWhereUniqueInput'];
}

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    createOneSelector: NexusGenRootTypes['Selector']; // Selector!
    createOneStep: NexusGenRootTypes['Step']; // Step!
    createOneTag: NexusGenRootTypes['Tag']; // Tag!
    createOneTest: NexusGenRootTypes['Test']; // Test!
    createOneUser: NexusGenRootTypes['User']; // User!
  }
  Query: { // field return type
    selector: NexusGenRootTypes['Selector'] | null; // Selector
    step: NexusGenRootTypes['Step'] | null; // Step
    tag: NexusGenRootTypes['Tag'] | null; // Tag
    test: NexusGenRootTypes['Test'] | null; // Test
    user: NexusGenRootTypes['User'] | null; // User
  }
  Selector: { // field return type
    css: string; // String!
    id: number; // Int!
  }
  Step: { // field return type
    action: string; // String!
    id: number; // Int!
    selector: NexusGenRootTypes['Selector']; // Selector!
    value: string; // String!
  }
  Tag: { // field return type
    id: number; // Int!
    name: string; // String!
  }
  Test: { // field return type
    id: number; // Int!
    name: string; // String!
    steps: NexusGenRootTypes['Step'][]; // [Step!]!
    tags: NexusGenRootTypes['Tag'][]; // [Tag!]!
  }
  User: { // field return type
    firstName: string; // String!
    id: number; // Int!
    lastName: string; // String!
    password: string; // String!
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneSelector: { // args
      data: NexusGenInputs['SelectorCreateInput']; // SelectorCreateInput!
    }
    createOneStep: { // args
      data: NexusGenInputs['StepCreateInput']; // StepCreateInput!
    }
    createOneTag: { // args
      data: NexusGenInputs['TagCreateInput']; // TagCreateInput!
    }
    createOneTest: { // args
      data: NexusGenInputs['TestCreateInput']; // TestCreateInput!
    }
    createOneUser: { // args
      data: NexusGenInputs['UserCreateInput']; // UserCreateInput!
    }
  }
  Query: {
    selector: { // args
      where: NexusGenInputs['SelectorWhereUniqueInput']; // SelectorWhereUniqueInput!
    }
    step: { // args
      where: NexusGenInputs['StepWhereUniqueInput']; // StepWhereUniqueInput!
    }
    tag: { // args
      where: NexusGenInputs['TagWhereUniqueInput']; // TagWhereUniqueInput!
    }
    test: { // args
      where: NexusGenInputs['TestWhereUniqueInput']; // TestWhereUniqueInput!
    }
    user: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
  }
  Test: {
    steps: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    tags: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Mutation" | "Query" | "Selector" | "Step" | "Tag" | "Test" | "User";

export type NexusGenInputNames = "SelectorCreateInput" | "SelectorCreateManyWithoutSelectorsInput" | "SelectorCreateOneWithoutSelectorInput" | "SelectorCreateWithoutStepsInput" | "SelectorCreateWithoutUserInput" | "SelectorWhereUniqueInput" | "StepCreateInput" | "StepCreateManyWithoutStepsInput" | "StepCreateWithoutSelectorInput" | "StepWhereUniqueInput" | "TagCreateInput" | "TagCreateManyWithoutTagsInput" | "TagCreateWithoutTestInput" | "TagWhereUniqueInput" | "TestCreateInput" | "TestCreateManyWithoutTestsInput" | "TestCreateOneWithoutTestInput" | "TestCreateWithoutStepsInput" | "TestCreateWithoutUserInput" | "TestWhereUniqueInput" | "UserCreateInput" | "UserCreateOneWithoutUserInput" | "UserCreateWithoutTagsInput" | "UserWhereUniqueInput";

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: {};
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}