// eslint-disable-next-line @typescript-eslint/no-restricted-imports
export * from "./index.ts"
export * from "./attributes.ts"
export * from "./declare.ts"
export * from "./fn.ts"
export * from "./generic.ts"
export * from "./keywords/Array.ts"
export * from "./keywords/builtins.ts"
export * from "./keywords/constructors.ts"
export * from "./keywords/FormData.ts"
export * from "./keywords/keywords.ts"
export * from "./keywords/number.ts"
export * from "./keywords/string.ts"
export * from "./keywords/ts.ts"
export * from "./keywords/TypedArray.ts"
export * from "./match.ts"
export * from "./module.ts"
export * from "./nary.ts"
export * from "./parser/ast/bounds.ts"
export * from "./parser/ast/default.ts"
export * from "./parser/ast/divisor.ts"
export * from "./parser/ast/generic.ts"
export * from "./parser/ast/infer.ts"
export * from "./parser/ast/keyof.ts"
export * from "./parser/ast/utils.ts"
export * from "./parser/ast/validate.ts"
export * from "./parser/definition.ts"
export * from "./parser/objectLiteral.ts"
export * from "./parser/property.ts"
export * from "./parser/reduce/dynamic.ts"
export * from "./parser/reduce/shared.ts"
export * from "./parser/reduce/static.ts"
export * from "./parser/shift/operand/date.ts"
export * from "./parser/shift/operand/enclosed.ts"
export * from "./parser/shift/operand/genericArgs.ts"
export * from "./parser/shift/operand/operand.ts"
export * from "./parser/shift/operand/unenclosed.ts"
export * from "./parser/shift/operator/bounds.ts"
export * from "./parser/shift/operator/brand.ts"
export * from "./parser/shift/operator/default.ts"
export * from "./parser/shift/operator/divisor.ts"
export * from "./parser/shift/operator/operator.ts"
export * from "./parser/shift/tokens.ts"
export * from "./parser/string.ts"
export * from "./parser/tupleExpressions.ts"
export * from "./parser/tupleLiteral.ts"
export * from "./scope.ts"
export * from "./type.ts"
export * from "./variants/array.ts"
export * from "./variants/base.ts"
export * from "./variants/date.ts"
export * from "./variants/instantiate.ts"
export * from "./variants/number.ts"
export * from "./variants/object.ts"
export * from "./variants/string.ts"

export type { Comparator } from "./attributes.ts"
export { json } from "./keywords/string.ts"
export { object } from "./keywords/ts.ts"
export type { InfixExpression } from "./parser/ast/infer.ts"
