name: manual release

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
            - name: Conventional Changelog Action
              id: changelog
              uses: TriPSs/conventional-changelog-action@d360fad3a42feca6462f72c97c165d60a02d4bf2
              # overriding some of the basic behaviors to just get the changelog
              with:
                  git-user-name: svc-cli-bot
                  git-user-email: svc_cli_bot@salesforce.com
                  github-token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
                  output-file: false
                  # always do the release, even if there are no semantic commits
                  skip-on-empty: false
                  tag-prefix: ""
            - uses: notiz-dev/github-action-json-property@2192e246737701f108a4571462b76c75e7376216
              id: packageVersion
              with:
                  path: "package.json"
                  prop_path: "version"
            - name: Create Github Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.packageVersion.outputs.prop }}
                  release_name: ${{ steps.packageVersion.outputs.prop }}
