import { isEmpty } from "../../../utils/deepEquals.js"
import type { DynamicTypeName } from "../../../utils/dynamicTypes.js"
import type { keyOrSet, keySet, RegexLiteral } from "../../../utils/generics.js"
import type { SerializablePrimitive } from "../../../utils/primitiveSerialization.js"
import type { AttributeKey, Attributes } from "./attributes.js"
import { divisorDifference } from "./divisor.js"
