export { type } from "./scopes/type.js"
export { space } from "./scopes/space.js"
export { declare } from "./scopes/declaration.js"
export { Root } from "./parser/root.js"
export type { ReferencesOf } from "./nodes/traverse/ast/references.js"
export type { NarrowFn } from "./nodes/traverse/check/customValidator.js"
