export { type } from "./scopes/type.js"
export { space } from "./scopes/root.js"
export { declare } from "./scopes/declaration.js"
export { Root } from "./parser/root.js"
export type { ReferencesOf } from "./nodes/traverse/references.js"
export type { NarrowFn as CustomConstraint } from "./nodes/traverse/check/customValidator.js"
