export { type, dynamic } from "./type.js"
export { space, dynamicSpace } from "./space/root.js"
export { declare } from "./declaration.js"
export { Root } from "./parser/root.js"
export type { ReferencesOf } from "./nodes/traverse/references.js"
