export { type, dynamic, type References, type Infer } from "./type.js"
export { space, def, dynamicSpace } from "./space.js"
export { declare } from "./declaration.js"
export { Root } from "./root.js"
export type { CustomValidator } from "./nodes/traversal/allows.js"
