export { scope } from "./scope.ts"
export { type, ark, arkScope } from "./scopes/ark.ts"
export type { Infer } from "./parse/definition.ts"
export type { Scope, Space } from "./scope.ts"
export { jsObjectsScope } from "./scopes/jsObjects.ts"
export { tsKeywordsScope } from "./scopes/tsKeywords.ts"
export { validationScope } from "./scopes/validation/validation.ts"
export { Problems, Problem } from "./nodes/problems.ts"
export { parseConfigTuple } from "./parse/ast/config.ts"
export type { validateBound } from "./parse/ast/bound.ts"
export type { validateDivisor } from "./parse/ast/divisor.ts"
