export { scope } from "./scope.js"
export { type, ark, arkScope } from "./scopes/ark.js"
export type { Inferred } from "./parse/definition.js"
export type { Scope, Space } from "./scope.js"
export { Type } from "./type.js"
export { jsObjectsScope } from "./scopes/jsObjects.js"
export { tsKeywordsScope } from "./scopes/tsKeywords.js"
export { validationScope } from "./scopes/validation/validation.js"
export { Problems, Problem } from "./nodes/problems.js"
export type { validateBound } from "./parse/ast/bound.js"
export type { validateDivisor } from "./parse/ast/divisor.js"
export { TypeNode } from "./nodes/type.js"
