name: release

on:
    push:
        branches: [main]

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout re-po
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 7.1.2

            - name: Setup Node.js 16
              uses: actions/setup-node@v4
              with:
                  node-version: 16
                  registry-url: "https://registry.npmjs.org"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Build packages
              run: pnpm build

            - name: Create and publish versions
              uses: changesets/action@1.3.0
              with:
                  commit: "chore: update versions"
                  title: "chore: update versions"
                  publish: pnpm ci:publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
